### ISSUE TITLE
Plagiarism?

### ISSUE THREAD

**Issue by MaxHalford** [Cauchemare/Light_FAMD#1]
Excuse me be this looks suspiciously similar to [prince](https://github.com/MaxHalford/prince), is there any particular reason why you created this repository?

**Comment by Cauchemare** [comment]
first all,I should thank you for refering to your codes ,sorry for not informing you in time,but if you read in depth my  codes,the whole structure and many logics  are not the same, Beside this,I created  truncated_famd could resolve big  datas by dividing it into small data.

**Comment by MaxHalford** [comment]
Ok fair enough but why not contribute to `prince` in that case? I don't see what's the point of copy/pasting a project and editing it a bit... I think it's a weird, especially considering you haven't mentioned the source of the code in your README. Suit yourself.

**Comment by Cauchemare** [comment]
Sorry for my ignorance and impertinency,i will mention the your code and write out the difference with yours
