### ISSUE TITLE
FAMD Guideline - object() takes no parameters

### ISSUE THREAD

**Issue by rodrigo-92** [Cauchemare/Light_FAMD#3]
Hi, I'm very interested in this lib. I'm trying to test the guideline example of FAMD explained [here](https://pypi.org/project/light-famd/#factor-analysis-of-mixed-data-famd) using Colab. But it throws me this error when famd object fits X dataframe:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-27-314c83adf277> in <module>()
----> 1 famd.fit(X)

3 frames
/usr/local/lib/python3.6/dist-packages/light_famd/famd.py in fit(self, X, y)
     43                              "you only have numerical data; you should consider using PCA")
     44 
---> 45         return super().fit(X)
     46 
     47     def fit_transform(self,X,y=None):

/usr/local/lib/python3.6/dist-packages/light_famd/mfa.py in fit(self, X, y)
     66                     engine=self.engine
     67                 )
---> 68             self.partial_factor_analysis_[name] = fa.fit(X.loc[:, cols])
     69 
     70         # Fit the global PCA

/usr/local/lib/python3.6/dist-packages/light_famd/mca.py in fit(self, X, y)
     20         self.one_hot_ = one_hot.OneHotEncoder().fit(X)
     21 
---> 22         _X_t=  self.one_hot_.transform(X)
     23 
     24         _0_freq_serie= (_X_t == 0).sum(axis=0)/ len(_X_t)

/usr/local/lib/python3.6/dist-packages/light_famd/one_hot.py in transform(self, X)
     27             columns=self.column_names_,
     28             index=X.index if isinstance(X, pd.DataFrame) else None,
---> 29             default_fill_value=0
     30         )

TypeError: object() takes no parameters

Is this related with environment version? Or is this probably a bug? Please I kindly request for help.

Best regards,

**Comment by Cauchemare** [comment]
since  your X dataframe only contains numerical data,you should  use PCA model rather than  FAMD module.

**Comment by elizastarr** [comment]
I have the same issue also when trying to run the example given in the [documentation](https://pypi.org/project/light-famd/#factor-analysis-of-mixed-data-famd). The data has both categorical and numerical features. 

Data:
`X_n = pd.DataFrame(data=np.random.randint(0,100,size=(10,2)),columns=list('AB'))
X_c =pd.DataFrame(np.random.choice(list('abcde'),size=(10,4),replace=True),columns =list('CDEF'))
X=pd.concat([X_n,X_c],axis=1)`
