### ISSUE TITLE
Update for latest pandas support

### ISSUE THREAD

**Issue by kabirmdasraful** [Cauchemare/Light_FAMD#6]
`import light_famd`
`from light_famd import PCA`
`import pandas as pd`
`import numpy as np`
`X_n = pd.DataFrame(data=np.random.randint(0,100,size=(10,2)),columns=list('AB'))`
`X_c =pd.DataFrame(np.random.choice(list('abcde'),size=(10,4),replace=True),columns =list('CDEF'))`
`X=pd.concat([X_n,X_c],axis=1)`
`famd = light_famd.FAMD(n_components=2)`
`famd.fit(X)`
After running this it shows following error. 
`TypeError: SparseDataFrame() takes no arguments`

It looks like because of the latest pandas version incompatibility. Do you have any plans to update the package?

**Comment by Cauchemare** [comment]
we had fixed this problem,you could try  again after updating your  light_famd package
